openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample Blog Service
  description: A sample API for Blog
  contact:
    name: Sample Author
    email: sample@example.com
    url: 'http://localhost'
servers:
  - url: 'http://localhost:8000'
tags:
  - name: post
paths:
  /posts:
    get:
      summary: Return all posts
      tags:
        - post
      description: .
      operationId: findPosts
      responses:
        '200':
          description: .
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      summary: Create a new post
      tags:
        - post
      description: Creates a new post.
      operationId: addPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPost'
      responses:
        '201':
          description: post response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Post:
      title: Post
      allOf:
        - type: object
          properties:
            id:
              type: integer
          required:
            - id
        - $ref: '#/components/schemas/NewPost'
    NewPost:
      title: NewPost
      type: object
      additionalProperties:
        type: string
      description: ''
      properties:
        title:
          type: string
        content:
          type: string
        test_multiple_of:
          type: integer
          multipleOf: 256
        test_multiple_of_decimals:
          type: number
          multipleOf: 0.2
        test_maximum:
          type: integer
          maximum: 100
        test_exclusive_maximum:
          type: integer
          maximum: 100
          exclusiveMaximum: true
        test_minimum:
          type: integer
          minimum: 10
        test_exclusive_minimum:
          type: integer
          minimum: 10
          exclusiveMinimum: true
        test_max_length:
          type: string
          maxLength: 10
        test_min_length:
          type: string
          minLength: 5
        test_pattern:
          type: string
          pattern: '^[A-Za-z]+'
        test_max_items:
          type: array
          maxItems: 5
          items:
            type: integer
        test_min_items:
          type: array
          minItems: 2
          items:
            type: integer
        test_unique_items:
          type: array
          uniqueItems: true
          items:
            type: integer
        test_enum:
          type: string
          enum:
            - dog
            - cat
            - bird
        test_format_byte:
          type: string
          format: byte
        test_format_date:
          type: string
          format: date
        test_format_datetime:
          type: string
          format: date-time
        test_format_email:
          type: string
          format: email
        test_format_ipv4:
          type: string
          format: ipv4
        test_format_ipv6:
          type: string
          format: ipv6
        test_format_uuid:
          type: string
          format: uuid
        test_format_postal:
          type: string
          format: postal
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: Error code
        message:
          type: string
          description: Error message
