openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample Blog Service
  description: A sample API for Blog
  contact:
    name: Sample Author
    email: sample@example.com
    url: 'http://localhost'
servers:
  - url: 'http://localhost:8000/api'
tags:
  - name: post
paths:
  /posts:
    get:
      summary: Return all posts
      tags:
        - post
      description: .
      operationId: findPosts
      responses:
        '200':
          description: .
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
components:
  schemas:
    Post:
      title: Post
      description: .
      type: object
      properties:
        id:
          type: integer
          description: .
        title:
          type: string
          description: .
        content:
          type: string
          description: .
      required:
        - id
        - title
