// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/pkg/errors"
)

// Defines values for NewPostTestEnum.
const (
	NewPostTestEnumBird NewPostTestEnum = "bird"

	NewPostTestEnumCat NewPostTestEnum = "cat"

	NewPostTestEnumDog NewPostTestEnum = "dog"
)

// Error defines model for Error.
type Error struct {

	// Error code
	Code int `json:"code"`

	// Error message
	Message string `json:"message"`
}

// NewPost defines model for NewPost.
type NewPost struct {
	Content                *string              `json:"content,omitempty"`
	TestEnum               *NewPostTestEnum     `json:"test_enum,omitempty"`
	TestExclusiveMaximum   *int                 `json:"test_exclusive_maximum,omitempty"`
	TestExclusiveMinimum   *int                 `json:"test_exclusive_minimum,omitempty"`
	TestFormatByte         *[]byte              `json:"test_format_byte,omitempty"`
	TestFormatDate         *openapi_types.Date  `json:"test_format_date,omitempty"`
	TestFormatDatetime     *time.Time           `json:"test_format_datetime,omitempty"`
	TestFormatEmail        *openapi_types.Email `json:"test_format_email,omitempty"`
	TestFormatIpv4         *string              `json:"test_format_ipv4,omitempty"`
	TestFormatIpv6         *string              `json:"test_format_ipv6,omitempty"`
	TestFormatPostal       *string              `json:"test_format_postal,omitempty"`
	TestFormatUuid         *string              `json:"test_format_uuid,omitempty"`
	TestMaxItems           *[]int               `json:"test_max_items,omitempty"`
	TestMaxLength          *string              `json:"test_max_length,omitempty"`
	TestMaximum            *int                 `json:"test_maximum,omitempty"`
	TestMinItems           *[]int               `json:"test_min_items,omitempty"`
	TestMinLength          *string              `json:"test_min_length,omitempty"`
	TestMinimum            *int                 `json:"test_minimum,omitempty"`
	TestMultipleOf         *int                 `json:"test_multiple_of,omitempty"`
	TestMultipleOfDecimals *float32             `json:"test_multiple_of_decimals,omitempty"`
	TestPattern            *string              `json:"test_pattern,omitempty"`
	TestUniqueItems        *[]int               `json:"test_unique_items,omitempty"`
	Title                  *string              `json:"title,omitempty"`
	AdditionalProperties   map[string]string    `json:"-"`
}

// NewPostTestEnum defines model for NewPost.TestEnum.
type NewPostTestEnum string

// Post defines model for Post.
type Post struct {
	// Embedded fields due to inline allOf schema
	Id int `json:"id"`
	// Embedded struct due to allOf(#/components/schemas/NewPost)
	NewPost `yaml:",inline"`
}

// FindPostsParams defines parameters for FindPosts.
type FindPostsParams struct {
	Limit *int `json:"limit,omitempty"`
}

// AddPostJSONBody defines parameters for AddPost.
type AddPostJSONBody NewPost

// AddPostJSONRequestBody defines body for AddPost for application/json ContentType.
type AddPostJSONRequestBody AddPostJSONBody

// Getter for additional properties for NewPost. Returns the specified
// element and whether it was found
func (a NewPost) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NewPost
func (a *NewPost) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NewPost to handle AdditionalProperties
func (a *NewPost) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["content"]; found {
		err = json.Unmarshal(raw, &a.Content)
		if err != nil {
			return errors.Wrap(err, "error reading 'content'")
		}
		delete(object, "content")
	}

	if raw, found := object["test_enum"]; found {
		err = json.Unmarshal(raw, &a.TestEnum)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_enum'")
		}
		delete(object, "test_enum")
	}

	if raw, found := object["test_exclusive_maximum"]; found {
		err = json.Unmarshal(raw, &a.TestExclusiveMaximum)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_exclusive_maximum'")
		}
		delete(object, "test_exclusive_maximum")
	}

	if raw, found := object["test_exclusive_minimum"]; found {
		err = json.Unmarshal(raw, &a.TestExclusiveMinimum)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_exclusive_minimum'")
		}
		delete(object, "test_exclusive_minimum")
	}

	if raw, found := object["test_format_byte"]; found {
		err = json.Unmarshal(raw, &a.TestFormatByte)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_format_byte'")
		}
		delete(object, "test_format_byte")
	}

	if raw, found := object["test_format_date"]; found {
		err = json.Unmarshal(raw, &a.TestFormatDate)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_format_date'")
		}
		delete(object, "test_format_date")
	}

	if raw, found := object["test_format_datetime"]; found {
		err = json.Unmarshal(raw, &a.TestFormatDatetime)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_format_datetime'")
		}
		delete(object, "test_format_datetime")
	}

	if raw, found := object["test_format_email"]; found {
		err = json.Unmarshal(raw, &a.TestFormatEmail)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_format_email'")
		}
		delete(object, "test_format_email")
	}

	if raw, found := object["test_format_ipv4"]; found {
		err = json.Unmarshal(raw, &a.TestFormatIpv4)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_format_ipv4'")
		}
		delete(object, "test_format_ipv4")
	}

	if raw, found := object["test_format_ipv6"]; found {
		err = json.Unmarshal(raw, &a.TestFormatIpv6)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_format_ipv6'")
		}
		delete(object, "test_format_ipv6")
	}

	if raw, found := object["test_format_postal"]; found {
		err = json.Unmarshal(raw, &a.TestFormatPostal)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_format_postal'")
		}
		delete(object, "test_format_postal")
	}

	if raw, found := object["test_format_uuid"]; found {
		err = json.Unmarshal(raw, &a.TestFormatUuid)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_format_uuid'")
		}
		delete(object, "test_format_uuid")
	}

	if raw, found := object["test_max_items"]; found {
		err = json.Unmarshal(raw, &a.TestMaxItems)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_max_items'")
		}
		delete(object, "test_max_items")
	}

	if raw, found := object["test_max_length"]; found {
		err = json.Unmarshal(raw, &a.TestMaxLength)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_max_length'")
		}
		delete(object, "test_max_length")
	}

	if raw, found := object["test_maximum"]; found {
		err = json.Unmarshal(raw, &a.TestMaximum)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_maximum'")
		}
		delete(object, "test_maximum")
	}

	if raw, found := object["test_min_items"]; found {
		err = json.Unmarshal(raw, &a.TestMinItems)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_min_items'")
		}
		delete(object, "test_min_items")
	}

	if raw, found := object["test_min_length"]; found {
		err = json.Unmarshal(raw, &a.TestMinLength)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_min_length'")
		}
		delete(object, "test_min_length")
	}

	if raw, found := object["test_minimum"]; found {
		err = json.Unmarshal(raw, &a.TestMinimum)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_minimum'")
		}
		delete(object, "test_minimum")
	}

	if raw, found := object["test_multiple_of"]; found {
		err = json.Unmarshal(raw, &a.TestMultipleOf)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_multiple_of'")
		}
		delete(object, "test_multiple_of")
	}

	if raw, found := object["test_multiple_of_decimals"]; found {
		err = json.Unmarshal(raw, &a.TestMultipleOfDecimals)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_multiple_of_decimals'")
		}
		delete(object, "test_multiple_of_decimals")
	}

	if raw, found := object["test_pattern"]; found {
		err = json.Unmarshal(raw, &a.TestPattern)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_pattern'")
		}
		delete(object, "test_pattern")
	}

	if raw, found := object["test_unique_items"]; found {
		err = json.Unmarshal(raw, &a.TestUniqueItems)
		if err != nil {
			return errors.Wrap(err, "error reading 'test_unique_items'")
		}
		delete(object, "test_unique_items")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return errors.Wrap(err, "error reading 'title'")
		}
		delete(object, "title")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return errors.Wrap(err, fmt.Sprintf("error unmarshaling field %s", fieldName))
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NewPost to handle AdditionalProperties
func (a NewPost) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Content != nil {
		object["content"], err = json.Marshal(a.Content)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'content'"))
		}
	}

	if a.TestEnum != nil {
		object["test_enum"], err = json.Marshal(a.TestEnum)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_enum'"))
		}
	}

	if a.TestExclusiveMaximum != nil {
		object["test_exclusive_maximum"], err = json.Marshal(a.TestExclusiveMaximum)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_exclusive_maximum'"))
		}
	}

	if a.TestExclusiveMinimum != nil {
		object["test_exclusive_minimum"], err = json.Marshal(a.TestExclusiveMinimum)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_exclusive_minimum'"))
		}
	}

	if a.TestFormatByte != nil {
		object["test_format_byte"], err = json.Marshal(a.TestFormatByte)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_format_byte'"))
		}
	}

	if a.TestFormatDate != nil {
		object["test_format_date"], err = json.Marshal(a.TestFormatDate)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_format_date'"))
		}
	}

	if a.TestFormatDatetime != nil {
		object["test_format_datetime"], err = json.Marshal(a.TestFormatDatetime)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_format_datetime'"))
		}
	}

	if a.TestFormatEmail != nil {
		object["test_format_email"], err = json.Marshal(a.TestFormatEmail)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_format_email'"))
		}
	}

	if a.TestFormatIpv4 != nil {
		object["test_format_ipv4"], err = json.Marshal(a.TestFormatIpv4)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_format_ipv4'"))
		}
	}

	if a.TestFormatIpv6 != nil {
		object["test_format_ipv6"], err = json.Marshal(a.TestFormatIpv6)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_format_ipv6'"))
		}
	}

	if a.TestFormatPostal != nil {
		object["test_format_postal"], err = json.Marshal(a.TestFormatPostal)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_format_postal'"))
		}
	}

	if a.TestFormatUuid != nil {
		object["test_format_uuid"], err = json.Marshal(a.TestFormatUuid)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_format_uuid'"))
		}
	}

	if a.TestMaxItems != nil {
		object["test_max_items"], err = json.Marshal(a.TestMaxItems)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_max_items'"))
		}
	}

	if a.TestMaxLength != nil {
		object["test_max_length"], err = json.Marshal(a.TestMaxLength)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_max_length'"))
		}
	}

	if a.TestMaximum != nil {
		object["test_maximum"], err = json.Marshal(a.TestMaximum)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_maximum'"))
		}
	}

	if a.TestMinItems != nil {
		object["test_min_items"], err = json.Marshal(a.TestMinItems)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_min_items'"))
		}
	}

	if a.TestMinLength != nil {
		object["test_min_length"], err = json.Marshal(a.TestMinLength)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_min_length'"))
		}
	}

	if a.TestMinimum != nil {
		object["test_minimum"], err = json.Marshal(a.TestMinimum)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_minimum'"))
		}
	}

	if a.TestMultipleOf != nil {
		object["test_multiple_of"], err = json.Marshal(a.TestMultipleOf)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_multiple_of'"))
		}
	}

	if a.TestMultipleOfDecimals != nil {
		object["test_multiple_of_decimals"], err = json.Marshal(a.TestMultipleOfDecimals)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_multiple_of_decimals'"))
		}
	}

	if a.TestPattern != nil {
		object["test_pattern"], err = json.Marshal(a.TestPattern)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_pattern'"))
		}
	}

	if a.TestUniqueItems != nil {
		object["test_unique_items"], err = json.Marshal(a.TestUniqueItems)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'test_unique_items'"))
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling 'title'"))
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling '%s'", fieldName))
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return all posts
	// (GET /posts)
	FindPosts(w http.ResponseWriter, r *http.Request, params FindPostsParams)
	// Create a new post
	// (POST /posts)
	AddPost(w http.ResponseWriter, r *http.Request)
	// Return a post
	// (GET /posts/{id})
	GetPost(w http.ResponseWriter, r *http.Request, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// FindPosts operation middleware
func (siw *ServerInterfaceWrapper) FindPosts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params FindPostsParams

	// ------------- Optional query parameter "limit" -------------
	if paramValue := r.URL.Query().Get("limit"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter limit: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindPosts(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// AddPost operation middleware
func (siw *ServerInterfaceWrapper) AddPost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddPost(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetPost operation middleware
func (siw *ServerInterfaceWrapper) GetPost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPost(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL     string
	BaseRouter  chi.Router
	Middlewares []MiddlewareFunc
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/posts", wrapper.FindPosts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/posts", wrapper.AddPost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/posts/{id}", wrapper.GetPost)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xWW4/rNBD+K9HAG9k2u7ArlCf2IEArLmfFeWNVKm8ybX3k29qTnpYq/x3ZcZImbWiB",
	"8xR77O+b8VxzgEJLoxUqcpAfwBUblCwsf7BWW78wVhu0xDGIC12i/5boCssNca0gby4n4SwF2huEHLgi",
	"XKOFOgWJzrH1JK497qCOLFdrqOsULL5V3GIJ+QtE/vb6ok7hN/z0rB15ZlaW3NMy8TyweMSZnjxIESo6",
	"e5PQ0RJVJf1p832BUq8hhYIRpPDKbQmLdAq5K0Tl+BaXku24jDSt8NdWRrbCFLort1l2zodjRq5OGVtZ",
	"ZGy3t9OEK20lo+XrnkJ0mi3kEART74qgko1AQXAFiLg8Bd4E6QU0SsbFANpILsC42X4zQAXBZdDDGPRw",
	"CWS0Iza0MIouAKuKlwNYEEyBJNstOaEMGdwtzhQe2z01p/cdFbOW7QdMAtWaNp5Bst0vcXOUNKfK29S7",
	"KmklV9cZy1U09m7KWK6OjeWqNfZ+0ta+TK4pB1kJ4kbgUq8CJG7fryC/u3+4BrYsseCSCTfGZ7P+VaqS",
	"r0dww4jQqtBs2yX8+fJ48we7+Wvx1WQWVIq/VXiVbwfuTKFBRm/7buGvcBJ4pg32R1237fj060csyCvo",
	"urAQ/rUv47nRZPfYsFGD58fNtOM+wJcWV5DDF/N+Ws3jqJq3NtWL3s5G4Nm5Wum2y7MiWBh7CDgmjcDv",
	"cBe+s0JLSEEx35rgQ5AljxVttPX+sh6xITL5fC50wcQmqEhH8+wxcRH5/JSstE3eiTAtWsMir5cmH9Bu",
	"eeFb3hata/C3s2yWeVptUDHDIYevgyj1mbEJnpz7hhJWa6TTkTqDgLbM759KyOFHrsrngPEslkkktC7E",
	"iHvEW4V2379dcMl9iBsHX65y73iLzmjlmlDfZdlosDJjBC+CRfOPTqv+V2OQtv8U5ufo72FfqE8iMAtJ",
	"5Sopmd1DDr8jVVYlTIjERB8QW/vXh8YcfiJMzN0h0/cWGaFLWKLwUwCfuvaxLGNB+DRGR+90uf9Xj78q",
	"tYd1Eut15PPbz6a21zl0iHdB0mptcn/FKkGfTXHzy3lGc6VwZ7AgLBOMd45j3ETqKFCnQa7TWDfzAy/r",
	"yeJps2Ui3D8hdeH+Hwn/X5z//ueJxG4eXJ8vbd80+soOPxTDPBqUeTcgzxV50I522/Kfb4n5t1mWNb24",
	"CcChVd6Yuaj/DgAA///E0040cwwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.Swagger, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewSwaggerLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.SwaggerLoader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadSwaggerFromData(specData)
	if err != nil {
		return
	}
	return
}

